#!/usr/bin/env python3
"""Generate the local-only Live Introductions static prototype."""

from __future__ import annotations

import argparse
from html import escape
from pathlib import Path
import re
import shutil

from live_introductions_catalog import (
    Action,
    ActionIntent,
    ActionScope,
    ATLAS_TARGET,
    Frame,
    Role,
    ShellAction,
    SurfaceContext,
    TransitionKind,
    all_frames,
    frames_for_role,
    review_transitions_for,
    routable_frames,
    shell_actions_for,
    transitions_for,
)


REPOSITORY_ROOT = Path(__file__).resolve().parents[1]
SOURCE_DIRECTORY = REPOSITORY_ROOT / "web" / "live-introductions-src"
ROLE_ORDER = (
    Role.VIEWER,
    Role.FEATURED_PARTICIPANT,
    Role.FACILITATOR,
    Role.CROSS_ROLE,
)
ROLE_LABELS = {
    Role.VIEWER: "Viewer",
    Role.FEATURED_PARTICIPANT: "Featured participant",
    Role.FACILITATOR: "Independent facilitator",
    Role.CROSS_ROLE: "Cross-role safety / integrity",
}
AUDIENCE_ORDER = (
    Role.VIEWER,
    Role.FEATURED_PARTICIPANT,
    Role.FACILITATOR,
)
PROTOTYPE_LIMITATION = (
    "No report, message, recording, location sharing, age check, "
    "study action, or safety operation actually occurs."
)
OUTPUT_MARKER = (
    "<!-- Generated by scripts/generate_live_introductions_prototype.py; "
    "replace only through that generator. -->"
)


def _render_template(template: str, replacements: dict[str, str]) -> str:
    rendered = template
    for name, value in replacements.items():
        rendered = rendered.replace("{{" + name + "}}", value)
    unresolved = sorted(set(re.findall(r"\{\{[A-Z_]+\}\}", rendered)))
    if unresolved:
        raise ValueError(f"Unresolved template placeholders: {', '.join(unresolved)}")
    return rendered


def _write_text(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content.rstrip() + "\n", encoding="utf-8", newline="\n")


def _validate_output_path(output: Path) -> None:
    resolved_output = output.resolve()
    allowed_repository_output = (REPOSITORY_ROOT / "dist").resolve()
    is_repository_or_ancestor = (
        resolved_output == REPOSITORY_ROOT
        or resolved_output in REPOSITORY_ROOT.parents
    )
    is_inside_repository = REPOSITORY_ROOT in resolved_output.parents
    is_allowed_repository_output = (
        resolved_output == allowed_repository_output
        or allowed_repository_output in resolved_output.parents
    )
    if is_repository_or_ancestor or (
        is_inside_repository and not is_allowed_repository_output
    ):
        raise ValueError(
            "Unsafe output path: generated files may use an external directory "
            "or a directory beneath the repository dist/ tree only"
        )


def _prepare_output(output: Path) -> None:
    _validate_output_path(output)
    output.parent.mkdir(parents=True, exist_ok=True)
    if output.exists():
        if not output.is_dir():
            raise ValueError(f"Output path is not a directory: {output}")
        existing_items = tuple(output.iterdir())
        if existing_items:
            atlas = output / "index.html"
            if not atlas.is_file() or OUTPUT_MARKER not in atlas.read_text(
                encoding="utf-8"
            ):
                raise ValueError(
                    "Refusing to replace a non-empty directory not created by "
                    "the Live Introductions generator"
                )
        shutil.rmtree(output)
    output.mkdir(parents=True)


def _target_href(target_id: str) -> str:
    if target_id == ATLAS_TARGET:
        return "../"
    return f"../{target_id.lower()}/"


def _audience_label(roles: set[Role]) -> str:
    ordered_roles = (*AUDIENCE_ORDER, Role.CROSS_ROLE)
    return ", ".join(ROLE_LABELS[role] for role in ordered_roles if role in roles)


def _render_shell_controls(frame: Frame) -> str:
    presentation = _presentation_for(frame)
    audience = presentation.audience
    items = []
    for action in shell_actions_for(frame.id, audience):
        audiences = {audience}
        attributes = (
            ' data-control-scope="shell"'
            f' data-label="{escape(action.label, quote=True)}"'
            f' data-shell-kind="{escape(action.kind.value, quote=True)}"'
            f' data-guard="{escape(action.guard.value, quote=True)}"'
            f' data-audiences="{escape(" ".join(sorted(role.value for role in audiences)), quote=True)}"'
        )
        audience_copy = escape(_audience_label(audiences))
        if action.target_id is None:
            control = (
                f'<span class="shell-status"{attributes}>'
                f"{escape(action.label)}"
                "</span>"
            )
        elif action.target_id == frame.id:
            control = (
                f'<span class="shell-link shell-link--current"{attributes}'
                f' data-target-id="{escape(action.target_id, quote=True)}"'
                ' aria-current="page">'
                f"{escape(action.label)}"
                "</span>"
            )
        elif action.guard.value != "always":
            control = (
                f'<span class="shell-link shell-link--guarded"{attributes}'
                f' data-target-id="{escape(action.target_id, quote=True)}"'
                ' aria-disabled="true">'
                f"{escape(action.label)}"
                "</span>"
            )
        else:
            control = (
                f'<a class="shell-link shell-link--{escape(action.kind.value, quote=True)}"'
                f'{attributes} data-target-id="{escape(action.target_id, quote=True)}"'
                f' href="{escape(_target_href(action.target_id), quote=True)}">'
                f"{escape(action.label)}"
                "</a>"
            )
        items.append(
            f'<li data-audience-label="{escape(audience_copy, quote=True)}">'
            f"{control}</li>"
        )

    return (
        '<nav class="shell-controls" aria-label="Persistent prototype controls">'
        '<p class="shell-heading">Persistent prototype controls</p>'
        f"<ul>{''.join(items)}</ul>"
        '<p class="shell-note">Static shell links only — no action is performed.</p>'
        "</nav>"
    )


def _action_key(action: Action) -> tuple[str, str, str, str, str]:
    return (
        action.label,
        action.target_id,
        action.kind.value,
        action.guard.value,
        action.scope.value,
    )


def _action_tone(label: str) -> str:
    normalized = label.casefold()
    destructive_terms = (
        "block ",
        "end ",
        "hide ",
        "remove ",
        "unmatch",
        "withdraw ",
        "close protocol incident",
    )
    caution_terms = (
        "cancel",
        "decline",
        "flag ",
        "pause",
        "report",
        "safety",
    )
    if normalized.startswith(destructive_terms):
        return "destructive"
    if normalized.startswith(caution_terms) or any(
        term in normalized for term in (" report", " safety")
    ):
        return "caution"
    return "standard"


def _body_controls_for(frame: Frame) -> tuple[tuple[Action, set[Role]], ...]:
    presentation = _presentation_for(frame)
    audiences = presentation.control_audiences or (presentation.audience,)
    controls = []
    for audience in audiences:
        if audience not in AUDIENCE_ORDER:
            continue
        controls.extend(
            (action.resolved_for(audience), {audience})
            for action in frame.actions
            if action.applies_to(audience)
            if not (
                presentation.context is SurfaceContext.NO_LIVE_CONTINUATION
                and action.scope is ActionScope.LIVE_DERIVED_CONTINUATION
            )
        )
    return tuple(controls)


def _render_body_controls(frame: Frame) -> str:
    presentation = frame.presentation
    if presentation is None:
        raise ValueError(f"Frame {frame.id} has no presentation metadata")

    controls = _body_controls_for(frame)
    if not controls:
        return (
            '<section class="control-deck" aria-labelledby="available-choices">'
            '<h2 id="available-choices">Available choices</h2>'
            "<p>No participant or facilitator control is declared for this state.</p>"
            "</section>"
        )

    rendered_controls = []
    primary_keys = {_action_key(action) for action in frame.primary_actions}
    for action, audiences in controls:
        prominence = (
            "primary" if _action_key(action) in primary_keys else "secondary"
        )
        tone = _action_tone(action.label)
        owner = (
            "Facilitator control"
            if action.kind is TransitionKind.FACILITATOR
            else "Participant control"
        )
        guard_copy = (
            "Available in this static state"
            if action.guard.value == "always"
            else f"Guard: {action.guard.value.replace('_', ' ')}"
        )
        audience_copy = escape(_audience_label(audiences))
        guard_allows_navigation = (
            action.guard.value == "always"
            or (
                presentation.context is SurfaceContext.NORMAL_COMPLETION
                and action.guard.value == "normal_completion_only"
            )
        )
        is_link = (
            action.intent is ActionIntent.NAVIGATION
            and action.kind in {TransitionKind.USER, TransitionKind.FACILITATOR}
            and action.target_id not in {frame.id, ATLAS_TARGET}
            and guard_allows_navigation
            and not (
                presentation.context is SurfaceContext.NO_LIVE_CONTINUATION
                and action.scope is ActionScope.CLOSURE_REFLECTION
            )
        )
        element = "a" if is_link else "div"
        href = (
            f' href="{escape(_target_href(action.target_id), quote=True)}"'
            if is_link
            else ' aria-disabled="true"'
        )
        control_copy = (
            "Static frame link"
            if is_link
            else "Noninteractive prototype control · not a link"
        )
        rendered_controls.append(
            f'<{element} class="product-action product-action--{escape(prominence)} '
            f'product-action--{escape(action.kind.value)} '
            f'product-action--{escape(tone)}'
            f'{" product-action--guarded" if not is_link else ""}"'
            ' data-control-scope="body"'
            f' data-label="{escape(action.label, quote=True)}"'
            f' data-target-id="{escape(action.target_id, quote=True)}"'
            f' data-transition-kind="{escape(action.kind.value, quote=True)}"'
            f' data-action-intent="{escape(action.intent.value, quote=True)}"'
            f' data-action-scope="{escape(action.scope.value, quote=True)}"'
            f' data-guard="{escape(action.guard.value, quote=True)}"'
            f' data-audiences="{escape(" ".join(sorted(role.value for role in audiences)), quote=True)}"'
            f"{href}>"
            f"<span>{escape(action.label)}</span>"
            f"<small>{control_copy} · {escape(owner)} · {audience_copy} · "
            f"{escape(guard_copy)}</small>"
            f"</{element}>"
        )

    return (
        '<section class="control-deck" aria-labelledby="available-choices">'
        '<div class="section-heading">'
        '<p class="eyebrow">Static navigation only</p>'
        '<h2 id="available-choices">Available choices</h2>'
        "</div>"
        "<p>Following a link opens another fictional frame. It performs no action.</p>"
        f'<div class="action-list">{"".join(rendered_controls)}</div>'
        "</section>"
    )

def _render_system_outcomes(frame_id: str) -> str:
    outcomes = transitions_for(frame_id, kind=TransitionKind.SYSTEM)
    if not outcomes:
        return (
            '<section class="system-outcomes" aria-labelledby="system-outcomes">'
            '<h2 id="system-outcomes">System-owned state outcomes</h2>'
            "<p>No automatic state outcome is declared for this frame.</p>"
            "</section>"
        )

    items = "".join(
        (
            '<li class="state-outcome"'
            ' data-transition-kind="system"'
            f' data-action-intent="{escape(action.intent.value, quote=True)}"'
            f' data-label="{escape(action.label, quote=True)}"'
            f' data-target-id="{escape(action.target_id, quote=True)}"'
            f' data-guard="{escape(action.guard.value, quote=True)}">'
            f"<strong>{escape(action.label)}</strong>"
            f"<span>Static outcome preview · automatic and non-clickable · "
            f"guard: {escape(action.guard.value.replace('_', ' '))} · "
            f"target frame: {escape(action.target_id)}</span>"
            "</li>"
        )
        for action in outcomes
    )
    return (
        '<section class="system-outcomes" aria-labelledby="system-outcomes">'
        '<div class="section-heading">'
        '<p class="eyebrow">Not a participant action</p>'
        '<h2 id="system-outcomes">System-owned state outcomes</h2>'
        "</div>"
        f"<ul>{items}</ul>"
        "</section>"
    )


def _render_review_links(frame_id: str) -> str:
    statuses = "".join(
        (
            '<span class="review-status" data-transition-kind="review"'
            f' data-action-intent="{escape(action.intent.value, quote=True)}"'
            f' data-label="{escape(action.label, quote=True)}"'
            f' data-target-id="{escape(action.target_id, quote=True)}"'
            f' data-guard="{escape(action.guard.value, quote=True)}"'
            ' aria-disabled="true">'
            f"{escape(action.label)}"
            "</span>"
        )
        for action in review_transitions_for(frame_id)
    )
    return (
        '<section class="review-navigation" aria-labelledby="review-navigation-title">'
        '<p id="review-navigation-title">Prototype review navigation — '
        "noninteractive and separate from product choices</p>"
        f"{statuses}"
        "</section>"
    )


def _presentation_for(frame: Frame):
    presentation = frame.presentation
    if presentation is None:
        raise ValueError(f"Frame {frame.id} has no presentation metadata")
    return presentation


def _render_statuses(frame: Frame) -> str:
    items = "".join(
        (
            "<div"
            + (' aria-current="true"' if status.current else "")
            + ">"
            f"<dt>{escape(status.label)}</dt>"
            f"<dd>{escape(status.value)}</dd>"
            "</div>"
        )
        for status in _presentation_for(frame).statuses
    )
    return f'<dl class="status-grid" aria-label="Current state">{items}</dl>'


def _render_choice_groups(frame: Frame) -> str:
    presentation = _presentation_for(frame)
    groups = []
    for group_index, group in enumerate(presentation.choice_groups, start=1):
        group_name = f"{frame.id.lower()}-choice-{group_index}"
        options = []
        for option_index, option in enumerate(group.options, start=1):
            control_id = f"{group_name}-{option_index}"
            checked = " checked" if option.selected else ""
            options.append(
                '<div class="choice-option">'
                f'<input id="{control_id}" type="{group.input_kind.value}"'
                f' name="{group_name}" value="{escape(option.value, quote=True)}"'
                f"{checked} disabled>"
                f'<label for="{control_id}"><span>{escape(option.label)}</span>'
                + (
                    f"<small>{escape(option.detail)}</small>"
                    if option.detail
                    else ""
                )
                + "</label></div>"
            )
        groups.append(
            '<fieldset class="choice-group" aria-disabled="true">'
            f"<legend>{escape(group.legend)}</legend>"
            f"{''.join(options)}"
            "</fieldset>"
        )
    return "".join(groups)


def _render_profile(frame: Frame) -> str:
    profile = _presentation_for(frame).profile
    if profile is None:
        return ""
    facts = "".join(f"<li>{escape(fact)}</li>" for fact in profile.facts)
    return (
        '<article class="profile-card" aria-labelledby="profile-card-title">'
        '<p class="surface-label">Profile preview</p>'
        f'<h2 id="profile-card-title">{escape(profile.name)}</h2>'
        f'<p class="profile-subtitle">{escape(profile.subtitle)}</p>'
        f"<ul>{facts}</ul>"
        f"<p>{escape(profile.bio)}</p>"
        "</article>"
    )


def _render_conversation(frame: Frame) -> str:
    conversation = _presentation_for(frame).conversation
    if conversation is None:
        return ""
    segment_rail = ""
    if conversation.segments:
        segments = "".join(
            (
                f'<li class="segment{" segment--current" if index == conversation.current_segment else ""}"'
                + (
                    ' aria-current="step"'
                    if index == conversation.current_segment
                    else ""
                )
                + ">"
                f'<span class="segment-number">{index + 1:02d}</span>'
                f"<span>{escape(label)}</span></li>"
            )
            for index, label in enumerate(conversation.segments)
        )
        segment_rail = (
            '<div class="conversation-spine">'
            '<p class="topic-tab">Conversation sequence</p>'
            f'<ol class="segment-rail">{segments}</ol></div>'
        )
    messages = "".join(
        (
            "<li>"
            f"<p><strong>{escape(message.speaker)}</strong>"
            + (
                f"<time>{escape(message.timestamp)}</time>"
                if message.timestamp
                else ""
            )
            + "</p>"
            f"<blockquote>{escape(message.body)}</blockquote>"
            "</li>"
        )
        for message in conversation.messages
    )
    return (
        '<section class="conversation-region" aria-labelledby="conversation-title">'
        f"{segment_rail}"
        '<div class="conversation-thread">'
        f'<h2 id="conversation-title">{escape(conversation.label)}</h2>'
        f'<ol class="message-list">{messages}</ol>'
        "</div></section>"
    )


def _render_text_controls(frame: Frame) -> str:
    controls = []
    for index, control in enumerate(
        _presentation_for(frame).text_controls,
        start=1,
    ):
        control_id = f"{frame.id.lower()}-text-{index}"
        if control.multiline:
            field = (
                f'<textarea id="{control_id}" readonly>'
                f"{escape(control.value)}</textarea>"
            )
        else:
            field = (
                f'<input id="{control_id}" type="text" '
                f'value="{escape(control.value, quote=True)}" readonly>'
            )
        controls.append(
            '<div class="text-control">'
            f'<label for="{control_id}">{escape(control.label)}</label>'
            f"{field}</div>"
        )
    return "".join(controls)


def _render_evidence(frame: Frame) -> str:
    evidence = _presentation_for(frame).evidence
    if evidence is None:
        return ""
    options = []
    for index, option in enumerate(evidence.options, start=1):
        control_id = f"{frame.id.lower()}-evidence-{index}"
        checked = " checked" if option.selected else ""
        options.append(
            '<div class="choice-option">'
            f'<input id="{control_id}" type="checkbox" '
            f'value="{escape(option.value, quote=True)}"{checked} disabled>'
            f'<label for="{control_id}">{escape(option.label)}</label>'
            "</div>"
        )
    return (
        '<fieldset class="evidence-checklist" aria-disabled="true">'
        f"<legend>{escape(evidence.legend)}</legend>"
        f"{''.join(options)}</fieldset>"
    )


def _render_panels(frame: Frame) -> str:
    return "".join(
        (
            '<article class="surface-panel">'
            f"<h2>{escape(panel.heading)}</h2>"
            + "".join(f"<p>{escape(line)}</p>" for line in panel.body)
            + "</article>"
        )
        for panel in _presentation_for(frame).panels
    )


def _render_product_surface(frame: Frame) -> str:
    presentation = _presentation_for(frame)
    semantics = (
        _render_profile(frame)
        + _render_conversation(frame)
        + _render_choice_groups(frame)
        + _render_text_controls(frame)
        + _render_evidence(frame)
    )
    return (
        '<section class="product-surface '
        f'product-surface--{escape(presentation.kind.value, quote=True)}"'
        f' data-surface-kind="{escape(presentation.kind.value, quote=True)}"'
        f' data-surface-context="{escape(presentation.context.value, quote=True)}"'
        f' data-audience="{escape(presentation.audience.value, quote=True)}"'
        ' data-first-viewport="priority"'
        ' aria-labelledby="product-surface-title">'
        '<header class="product-surface__header">'
        f'<p class="eyebrow">{escape(presentation.eyebrow)}</p>'
        f'<h1 id="product-surface-title">{escape(presentation.heading)}</h1>'
        f'<p class="surface-summary">{escape(presentation.summary)}</p>'
        "</header>"
        f'<div class="surface-native-ui">{semantics}</div>'
        f"{_render_statuses(frame)}"
        f'<div class="surface-panels">{_render_panels(frame)}</div>'
        "</section>"
    )


def _render_frame_interface(frame: Frame) -> str:
    presentation = _presentation_for(frame)
    provenance_attribute = (
        ' data-provenance-variant="normal_completion"'
        if presentation.context is SurfaceContext.NORMAL_COMPLETION
        else ""
    )
    role_label = (
        "Profile owner"
        if presentation.context is SurfaceContext.ORDINARY_APP
        else ROLE_LABELS[presentation.audience]
    )
    return (
        '<article class="product-frame"'
        f' data-role="{escape(frame.role.value, quote=True)}"'
        f' data-phase="{escape(frame.phase.value, quote=True)}"'
        f"{provenance_attribute}>"
        '<header class="frame-intro">'
        f'<p class="frame-code"><span>Frame {escape(frame.id)}</span>'
        f"<span>Role · {escape(role_label)}</span>"
        f"<span>Phase · {escape(frame.phase.value.replace('_', ' '))}</span></p>"
        f'<p class="screen-title">{escape(frame.title)}</p>'
        "</header>"
        f"{_render_product_surface(frame)}"
        "</article>"
    )


def _render_contract(frame: Frame) -> str:
    contract = _presentation_for(frame).contract
    if contract is None:
        raise ValueError(f"Frame {frame.id} has no contract metadata")
    contract_sections = (
        "<section><h2>Privacy</h2>"
        f"<p>{escape(contract.privacy)}</p></section>"
        "<section><h2>Accessibility</h2>"
        f"<p>{escape(contract.accessibility)}</p></section>"
        "<section><h2>Failure / exit behavior</h2>"
        f"<p>{escape(contract.failure_exit)}</p></section>"
        "<section><h2>Transition semantics</h2>"
        "<p>Only typed navigation edges with distinct, non-atlas destinations "
        "are links. Self-targets, atlas-target mutations, unsupported mutations, "
        "automatic outcomes, and review edges are labeled noninteractive states. "
        "A guarded continuation links only on its direct normal-completion variant.</p>"
        f"<p>Terminal class: {escape(frame.terminal_class.value.replace('_', ' '))}. "
        f"Continuation: {escape(frame.continuation.value.replace('_', ' '))}.</p>"
        "</section>"
        "<section><h2>Prototype limitation</h2>"
        f"<p>{escape(PROTOTYPE_LIMITATION)}</p>"
        "<p>Every linked choice opens another static page; preview controls "
        "do not send or save anything.</p></section>"
    )
    return (
        '<details class="wireframe-contract">'
        "<summary>Wireframe contract and limitations</summary>"
        f'<div class="contract-grid">{contract_sections}</div>'
        "</details>"
        '<section class="print-contract" data-print-mirror="wireframe-contract" '
        'aria-hidden="true">'
        "<h2>Wireframe contract and limitations</h2>"
        f'<div class="contract-grid">{contract_sections}</div>'
        "</section>"
    )


def generate(output: Path) -> None:
    """Write the deterministic static atlas and every catalog frame."""

    atlas_template = (SOURCE_DIRECTORY / "index.html").read_text(encoding="utf-8")
    frame_template = (SOURCE_DIRECTORY / "frame.html").read_text(encoding="utf-8")
    stylesheet = (SOURCE_DIRECTORY / "app.css").read_bytes()

    atlas_navigation = (
        '<span aria-current="page">Overview</span>'
        + "".join(
            f'<a href="#{escape(role.value)}">{escape(ROLE_LABELS[role])}</a>'
            for role in ROLE_ORDER
        )
    )
    atlas_groups = []
    for role in ROLE_ORDER:
        frames = frames_for_role(role)
        cards = "".join(
            (
                '<article class="atlas-card">'
                f'<p class="frame-code">{escape(frame.id)}</p>'
                f"<h3>{escape(frame.title)}</h3>"
                f"<p>{escape(frame.summary)}</p>"
                f'<a href="{escape(frame.id.lower())}/">Open {escape(frame.id)}</a>'
                "</article>"
            )
            for frame in frames
        )
        atlas_groups.append(
            f'<section id="{escape(role.value)}" class="atlas-group">'
            f"<h2>{escape(ROLE_LABELS[role])} · {len(frames)} frames</h2>"
            f'<div class="atlas-grid">{cards}</div>'
            "</section>"
        )
    atlas = _render_template(
        atlas_template,
        {
            "ATLAS_NAVIGATION": atlas_navigation,
            "ATLAS_INTRODUCTION": (
                "A synthetic-only review artifact with 39 fictional interface states: "
                "20 viewer, 8 featured-participant, 8 facilitator, and 3 cross-role "
                "safety or integrity frames. No real people, study, or product "
                "capability is represented."
            ),
            "FRAME_GROUPS": "".join(atlas_groups),
            "PROTOTYPE_LIMITATION": (
                "Static navigation demonstrates wireframe states only; no action is performed."
            ),
        },
    )
    generated_pages = {"index.html": f"{OUTPUT_MARKER}\n{atlas}"}

    for frame in routable_frames():
        frame_page = _render_template(
            frame_template,
            {
                "DOCUMENT_TITLE": f"{escape(frame.id)} — {escape(frame.title)}",
                "FRAME_ID": escape(frame.id),
                "SHELL_TITLE": escape(_presentation_for(frame).brand_label),
                "SHELL_CONTROLS": _render_shell_controls(frame),
                "FRAME_NAVIGATION": (
                    '<a href="../">Frame atlas</a>'
                    f'<span aria-current="page">{escape(frame.id)}</span>'
                ),
                "FRAME_INTERFACE": (
                    _render_frame_interface(frame)
                    + _render_body_controls(frame)
                    + _render_system_outcomes(frame.id)
                ),
                "FRAME_CONTRACT": _render_contract(frame),
                "REVIEW_LINKS": _render_review_links(frame.id),
            },
        )
        generated_pages[f"{frame.id.lower()}/index.html"] = frame_page

    _prepare_output(output)
    for relative_path, content in generated_pages.items():
        _write_text(output / relative_path, content)
    (output / "app.css").write_bytes(stylesheet)


def _parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Generate the Live Introductions static synthetic prototype."
    )
    parser.add_argument(
        "--output",
        required=True,
        type=Path,
        help="Directory that receives the generated static artifact.",
    )
    return parser.parse_args()


def main() -> int:
    args = _parse_args()
    generate(args.output.expanduser().resolve())
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
