export const SYNTHETIC_PROFILES = Object.freeze([
  {
    id: "p1",
    displayName: "Alex",
    ageBand: "25–34",
    about: "Coffee, hiking, movie nights, and honest communication.",
    alignment: 89,
    alignmentScore: 89,
    intents: ["casual_dating", "movie_night", "cuddles"],
    immediateIntent: "casual_dating",
    relationalOpenness: "open_to_more",
    acceptedImmediateIntents: ["casual_tonight", "friends_with_benefits", "casual_dating", "open_dating"],
    acceptedRelationalOpenness: ["casual_only", "open_to_more", "relationship_possible"],
    boundaries: ["condoms_required", "recent_testing_discussion", "public_first_meet", "no_drugs"],
    requiredBoundaries: ["condoms_required", "public_first_meet"],
    lifestyleTags: ["coffee", "hiking", "movie_night", "live_music"],
    distanceKm: 7,
  },
  {
    id: "p2",
    displayName: "Jordan",
    ageBand: "25–34",
    about: "Trade work, live music, fitness, and building things.",
    alignment: 77,
    alignmentScore: 77,
    intents: ["friends_with_benefits", "concert_or_event"],
    immediateIntent: "friends_with_benefits",
    relationalOpenness: "relationship_possible",
    acceptedImmediateIntents: ["friends_with_benefits", "casual_dating", "open_dating"],
    acceptedRelationalOpenness: ["open_to_more", "relationship_possible", "seeking_relationship"],
    boundaries: ["condoms_required", "public_first_meet", "sober_meetup", "no_drugs"],
    requiredBoundaries: ["condoms_required"],
    lifestyleTags: ["live_music", "fitness", "building_things", "concerts"],
    distanceKm: 14,
  },
  {
    id: "p3",
    displayName: "Morgan",
    ageBand: "25–34",
    about: "Museum afternoons, cooking experiments, gaming, and clear boundaries.",
    alignment: 94,
    alignmentScore: 94,
    intents: ["open_dating", "dinner_or_drinks", "gaming"],
    immediateIntent: "open_dating",
    relationalOpenness: "open_to_more",
    acceptedImmediateIntents: ["casual_dating", "open_dating", "relationship_focused"],
    acceptedRelationalOpenness: ["open_to_more", "relationship_possible", "seeking_relationship"],
    boundaries: ["condoms_required", "recent_testing_discussion", "public_first_meet", "no_smoking", "no_drugs"],
    requiredBoundaries: ["public_first_meet", "no_drugs"],
    lifestyleTags: ["museums", "cooking", "gaming", "movie_night"],
    distanceKm: 24,
  },
]);

export const SKIN_ITEMS = Object.freeze([
  { id: "neon-orbit", title: "Neon Orbit", type: "Profile skin", price: "$1.99 mock" },
  { id: "coffee-fox", title: "Coffee Fox", type: "Avatar", price: "Free mock" },
  { id: "midnight-chat", title: "Midnight Chat", type: "Chat skin", price: "$0.99 mock" },
]);

export const QUESTIONNAIRE = Object.freeze([
  {
    id: "political_alignment_importance",
    prompt: "How important is political alignment?",
    options: ["Not important", "Somewhat important", "Very important", "Dealbreaker"],
  },
  {
    id: "education_path",
    prompt: "Which education or training path fits you?",
    options: ["College/university", "Trade/apprenticeship", "Self-taught", "A mix"],
  },
  {
    id: "intimacy_style",
    prompt: "Which adult intimacy style sounds most compatible?",
    options: ["Mostly vanilla", "Adventurous", "Kink/BDSM-aware", "Depends on trust"],
  },
]);
